### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Comment by javier-godoy** [comment]
d717637 build(demo): add *commons-demo* dependency
9b466a0 `test(demo)` instead of `refactor`
bf15d4e (change to assembly.xml should be commited in b01ccf1)

**Comment by ngonzalezpazFC** [comment]
> 
> 
> [d717637](https://github.com/FlowingCode/FilterableLayoutAddon/commit/d717637f3b595375a3ba2bdf71475c3cae90d3b8) build(demo): add _commons-demo_ dependency
> [9b466a0](https://github.com/FlowingCode/FilterableLayoutAddon/commit/9b466a00fee4fbe956f279c68afb1156cfb942c7) `test(demo)` instead of `refactor`
> [bf15d4e](https://github.com/FlowingCode/FilterableLayoutAddon/commit/bf15d4ecf4d5a02b1a9044645cd716e87e2fa36f) (change to assembly.xml should be commited in [b01ccf1](https://github.com/FlowingCode/FilterableLayoutAddon/commit/b01ccf188d182d1c8e0dc0a1ae0134a06edecb9b))

Done

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please review

LGTM

**Pull request merged**
